import { StartupRole } from './types';

export const DEFAULT_STARTUP_ROLES: StartupRole[] = [
  {
    id: 'supabase-founding',
    company: 'Supabase',
    website: 'https://supabase.com',
    founderName: 'Paul Copplestone',
    founderRole: 'Co-founder & CEO',
    email: 'paul@supabase.com',
    roleTitle: 'Founding Engineer (Compute & Edge)',
    location: 'Remote (Global)',
    isRemote: true,
    salaryRange: '$160k - $210k + 0.15% - 0.4%',
    stage: 'Series C (YC S20)',
    description: 'Scaling Postgres edge functions, distributed compute primitives, and real-time database replication.',
    requiredSkills: ['Rust', 'TypeScript', 'PostgreSQL', 'Distributed Systems', 'Docker'],
    recentMilestone: 'Announced Edge Runtime v2 and multi-region read replicas',
    category: 'Systems & Infra'
  },
  {
    id: 'resend-product-eng',
    company: 'Resend',
    website: 'https://resend.com',
    founderName: 'Zeno Rocha',
    founderRole: 'Founder & CEO',
    email: 'zeno@resend.com',
    roleTitle: 'Founding Product Engineer',
    location: 'Remote',
    isRemote: true,
    salaryRange: '$170k - $220k + 0.2% - 0.5%',
    stage: 'Series A (YC W23)',
    description: 'Building developer-first email infrastructure, React Email templates, and ultra-fast real-time delivery logs.',
    requiredSkills: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'API Design'],
    recentMilestone: 'Crossed 100M emails delivered daily with sub-100ms API latency',
    category: 'Product Engineering'
  },
  {
    id: 'cognition-ai-eng',
    company: 'Cognition AI',
    website: 'https://cognition.ai',
    founderName: 'Scott Wu',
    founderRole: 'Co-Founder & CEO',
    email: 'scott@cognition.ai',
    roleTitle: 'AI Toolchain & Sandbox Engineer',
    location: 'San Francisco, CA / Remote',
    isRemote: true,
    salaryRange: '$190k - $260k + Equity',
    stage: 'Series A ($175M raised)',
    description: 'Architecting isolated micro-VM sandboxes, deterministic code execution environments, and autonomous agent loops.',
    requiredSkills: ['TypeScript', 'Python', 'Docker', 'Kernel Sandboxing', 'LLM Prompt Systems', 'Linux'],
    recentMilestone: 'Rolled out background autonomous task synthesis and MCP integrations',
    category: 'AI / ML'
  },
  {
    id: 'modal-infra',
    company: 'Modal Labs',
    website: 'https://modal.com',
    founderName: 'Erik Bernhardsson',
    founderRole: 'Founder & CEO',
    email: 'erik@modal.com',
    roleTitle: 'Serverless Systems Engineer',
    location: 'New York / Remote',
    isRemote: true,
    salaryRange: '$180k - $240k + 0.2% - 0.5%',
    stage: 'Series A (Redpoint)',
    description: 'Building instant cold-start GPU/CPU serverless compute containers for AI models and data pipelines.',
    requiredSkills: ['Rust', 'Python', 'Linux Kernel', 'Distributed Systems', 'C++'],
    recentMilestone: 'Achieved sub-second cold starts for 70B parameter models',
    category: 'Systems & Infra'
  },
  {
    id: 'cursorteam-eng',
    company: 'Anysphere (Cursor)',
    website: 'https://cursor.com',
    founderName: 'Michael Truell',
    founderRole: 'Co-Founder & CEO',
    email: 'michael@anysphere.co',
    roleTitle: 'Core IDE & Systems Engineer',
    location: 'San Francisco, CA',
    isRemote: false,
    salaryRange: '$200k - $280k + Generous Equity',
    stage: 'Series A (OpenAI Fund)',
    description: 'Building the next-generation AI code editor with real-time multi-file diff models and shadow workspaces.',
    requiredSkills: ['TypeScript', 'VSCode Architecture', 'C++', 'AST Parsers', 'Fast Inference'],
    recentMilestone: 'Ranked #1 most-loved AI developer environment in 2024–2025',
    category: 'Founding Engineer'
  },
  {
    id: 'calcom-fullstack',
    company: 'Cal.com',
    website: 'https://cal.com',
    founderName: 'Peer Richelsen',
    founderRole: 'Co-Founder & CEO',
    email: 'peer@cal.com',
    roleTitle: 'Full-Stack Platform Engineer',
    location: 'Remote (Worldwide)',
    isRemote: true,
    salaryRange: '$140k - $190k + Stock Options',
    stage: 'Series A (OSS Capital)',
    description: 'Leading open-source scheduling infrastructure, webhooks, calendar syncing algorithms, and enterprise apps.',
    requiredSkills: ['Next.js', 'React', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
    recentMilestone: 'Surpassed 35,000 GitHub stars and 5M booked appointments',
    category: 'Full-Stack'
  },
  {
    id: 'dub-platform',
    company: 'Dub.co',
    website: 'https://dub.co',
    founderName: 'Steven Tey',
    founderRole: 'Founder & CEO',
    email: 'steven@dub.co',
    roleTitle: 'Lead Product & Frontend Engineer',
    location: 'Remote',
    isRemote: true,
    salaryRange: '$150k - $200k + Equity',
    stage: 'Seed (Tiny VC / YC)',
    description: 'Crafting pixel-perfect edge link analytics, QR code engines, and hyper-fast dashboard experiences.',
    requiredSkills: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Edge Compute', 'Tinybird'],
    recentMilestone: 'Powering short-links and deep analytics for Vercel, Raycast, and Superhuman',
    category: 'Frontend'
  },
  {
    id: 'v0-generative',
    company: 'Linear Labs',
    website: 'https://linear.app',
    founderName: 'Karri Saarinen',
    founderRole: 'Co-Founder & CEO',
    email: 'karri@linear.app',
    roleTitle: 'Client Performance & Sync Engineer',
    location: 'Remote (US/EU)',
    isRemote: true,
    salaryRange: '$180k - $230k + Equity',
    stage: 'Series B (Accel)',
    description: 'Maintaining zero-latency local-first SQLite sync, keyboard command palettes, and desktop clients.',
    requiredSkills: ['TypeScript', 'Electron', 'Local-first Architecture', 'SQLite', 'React'],
    recentMilestone: 'Released Customer Requests and Project Updates 2.0 with instant optimistic UI',
    category: 'Frontend'
  }
];
