import { StartupRole } from './types';

export const DEFAULT_STARTUP_ROLES: StartupRole[] = [
  {
    id: 'resend-eng',
    company: 'Resend',
    website: 'https://resend.com',
    founderName: 'Zeno Rocha',
    founderRole: 'Founder & CEO',
    email: 'zeno@resend.com',
    roleTitle: 'Founding Product Engineer',
    location: 'Remote (Worldwide)',
    isRemote: true,
    salaryRange: '$160k - $210k + 0.25% - 0.5%',
    stage: 'Series A (YC W23)',
    description: 'Building developer-first email infrastructure, React Email templates, and ultra-fast real-time delivery logs.',
    requiredSkills: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'PostgreSQL'],
    recentMilestone: 'Delivering 100M+ emails daily with sub-100ms API latency',
    category: 'Full-Stack'
  },
  {
    id: 'supabase-infra',
    company: 'Supabase',
    website: 'https://supabase.com',
    founderName: 'Paul Copplestone',
    founderRole: 'Co-founder & CEO',
    email: 'paul@supabase.com',
    roleTitle: 'Systems & Compute Engineer',
    location: 'Remote',
    isRemote: true,
    salaryRange: '$170k - $220k + Equity',
    stage: 'Series C (YC S20)',
    description: 'Scaling Postgres edge compute primitives, distributed query caching, and real-time database replication.',
    requiredSkills: ['Rust', 'PostgreSQL', 'Go', 'Docker', 'Distributed Systems', 'Linux'],
    recentMilestone: 'Rolled out multi-region read replicas and edge functions v2',
    category: 'Backend & Systems'
  },
  {
    id: 'cognition-ai',
    company: 'Cognition AI',
    website: 'https://cognition.ai',
    founderName: 'Scott Wu',
    founderRole: 'Co-Founder & CEO',
    email: 'scott@cognition.ai',
    roleTitle: 'AI Toolchain & Sandboxing Engineer',
    location: 'San Francisco, CA / Remote',
    isRemote: true,
    salaryRange: '$200k - $280k + Generous Equity',
    stage: 'Series A ($175M raised)',
    description: 'Architecting isolated micro-VM execution sandboxes and deterministic agent tool dispatch pipelines.',
    requiredSkills: ['TypeScript', 'Python', 'Docker', 'Kernel Sandboxing', 'LLM Prompt Systems', 'Linux'],
    recentMilestone: 'Launched autonomous background task synthesis and MCP integrations',
    category: 'AI / ML'
  },
  {
    id: 'modal-systems',
    company: 'Modal Labs',
    website: 'https://modal.com',
    founderName: 'Erik Bernhardsson',
    founderRole: 'Founder & CEO',
    email: 'erik@modal.com',
    roleTitle: 'Serverless Infrastructure Engineer',
    location: 'New York, NY / Remote',
    isRemote: true,
    salaryRange: '$180k - $240k + 0.2% - 0.4%',
    stage: 'Series A (Redpoint)',
    description: 'Building instant cold-start GPU/CPU container virtualization for high-throughput AI pipelines.',
    requiredSkills: ['Rust', 'Python', 'Linux Kernel', 'Distributed Systems', 'C++'],
    recentMilestone: 'Sub-second cold starts for 70B parameter open-weights models',
    category: 'Backend & Systems'
  },
  {
    id: 'cursor-ide',
    company: 'Cursor (Anysphere)',
    website: 'https://cursor.com',
    founderName: 'Michael Truell',
    founderRole: 'Co-Founder & CEO',
    email: 'michael@anysphere.co',
    roleTitle: 'Core IDE & Diff Engine Engineer',
    location: 'San Francisco, CA',
    isRemote: false,
    salaryRange: '$210k - $290k + Equity',
    stage: 'Series A (OpenAI Fund)',
    description: 'Engineering the next-generation AI code editor with real-time speculative editing and AST tree diffs.',
    requiredSkills: ['TypeScript', 'VSCode Architecture', 'C++', 'AST Parsers', 'Fast Inference'],
    recentMilestone: 'Surpassed 1M+ active developers relying on Cursor daily',
    category: 'Founding Engineer'
  },
  {
    id: 'dub-frontend',
    company: 'Dub.co',
    website: 'https://dub.co',
    founderName: 'Steven Tey',
    founderRole: 'Founder & CEO',
    email: 'steven@dub.co',
    roleTitle: 'Lead Product & Frontend Engineer',
    location: 'Remote (Worldwide)',
    isRemote: true,
    salaryRange: '$150k - $195k + 0.5% - 1.0%',
    stage: 'Seed (YC W24)',
    description: 'Crafting ultra-fast short link analytics, real-time edge geo-routing, and polished dashboard interactions.',
    requiredSkills: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Edge Runtime', 'Tinybird'],
    recentMilestone: 'Powering short-links for Vercel, Raycast, and Superhuman',
    category: 'Frontend'
  },
  {
    id: 'linear-client',
    company: 'Linear',
    website: 'https://linear.app',
    founderName: 'Karri Saarinen',
    founderRole: 'Co-Founder & CEO',
    email: 'karri@linear.app',
    roleTitle: 'Client Performance & Local-First Engineer',
    location: 'Remote (US/EU)',
    isRemote: true,
    salaryRange: '$180k - $240k + Equity',
    stage: 'Series B (Accel)',
    description: 'Maintaining zero-latency local-first SQLite sync, keyboard commands, and high-FPS desktop UI.',
    requiredSkills: ['TypeScript', 'Electron', 'Local-first Architecture', 'SQLite', 'React'],
    recentMilestone: 'Shipped Customer Requests and Project Updates 2.0 with instant optimistic updates',
    category: 'Frontend'
  },
  {
    id: 'calcom-platform',
    company: 'Cal.com',
    website: 'https://cal.com',
    founderName: 'Peer Richelsen',
    founderRole: 'Co-Founder & CEO',
    email: 'peer@cal.com',
    roleTitle: 'Full-Stack Platform Engineer',
    location: 'Remote (Worldwide)',
    isRemote: true,
    salaryRange: '$140k - $185k + Stock Options',
    stage: 'Series A (OSS Capital)',
    description: 'Maintaining open-source scheduling infrastructure, webhooks, calendar syncing, and app ecosystem.',
    requiredSkills: ['Next.js', 'React', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
    recentMilestone: 'Over 35,000 GitHub stars and 5M booked appointments',
    category: 'Full-Stack'
  },
  {
    id: 'vapi-ai',
    company: 'Vapi',
    website: 'https://vapi.ai',
    founderName: 'Jordan Singer',
    founderRole: 'Founder & CEO',
    email: 'jordan@vapi.ai',
    roleTitle: 'Real-time Voice AI & WebRTC Engineer',
    location: 'San Francisco, CA / Remote',
    isRemote: true,
    salaryRange: '$170k - $230k + Equity',
    stage: 'Series A (Bessemer)',
    description: 'Ultra-low latency voice agents orchestrating WebRTC streams, streaming speech-to-text, and fast LLM token audio pipelines.',
    requiredSkills: ['WebRTC', 'Python', 'Go', 'TypeScript', 'Audio DSP', 'Node.js'],
    recentMilestone: 'Achieved sub-450ms end-to-end voice latency globally',
    category: 'AI / ML'
  },
  {
    id: 'langfuse-fullstack',
    company: 'Langfuse',
    website: 'https://langfuse.com',
    founderName: 'Marc Klingen',
    founderRole: 'Co-Founder & CEO',
    email: 'marc@langfuse.com',
    roleTitle: 'Full-Stack LLM Observability Engineer',
    location: 'Berlin / Remote',
    isRemote: true,
    salaryRange: '$130k - $175k + Equity',
    stage: 'Seed (YC W23)',
    description: 'Building open-source LLM observability, trace analytics, prompt management, and evaluation metrics.',
    requiredSkills: ['TypeScript', 'Next.js', 'ClickHouse', 'PostgreSQL', 'Docker', 'OpenTelemetry'],
    recentMilestone: 'Ingesting over 500M agent traces monthly across 5,000+ teams',
    category: 'Full-Stack'
  },
  {
    id: 'axiom-infra',
    company: 'Axiom',
    website: 'https://axiom.co',
    founderName: 'Neil Ferguson',
    founderRole: 'Co-Founder & CEO',
    email: 'neil@axiom.co',
    roleTitle: 'Cloud Storage & Query Engine Engineer',
    location: 'Remote',
    isRemote: true,
    salaryRange: '$180k - $240k + Equity',
    stage: 'Series A',
    description: 'Ultra-efficient serverless log and event analytics engine built on object storage with high compression ratios.',
    requiredSkills: ['Go', 'Rust', 'Distributed Systems', 'Object Storage (S3)', 'Kubernetes'],
    recentMilestone: 'Querying petabytes of telemetry in sub-second response times',
    category: 'DevOps & Infra'
  },
  {
    id: 'posthog-growth',
    company: 'PostHog',
    website: 'https://posthog.com',
    founderName: 'James Hawkins',
    founderRole: 'Co-Founder & CEO',
    email: 'james@posthog.com',
    roleTitle: 'Founding Growth & Product Engineer',
    location: 'Remote (Worldwide)',
    isRemote: true,
    salaryRange: '$165k - $215k + Generous Equity',
    stage: 'Series B (Y Combinator)',
    description: 'Building open-source product analytics, session replays, feature flags, and survey tools.',
    requiredSkills: ['Python', 'TypeScript', 'React', 'ClickHouse', 'Django', 'Kafka'],
    recentMilestone: 'Profitable open-source company serving 100k+ engineering teams',
    category: 'Full-Stack'
  }
];
